[server]
headless = true
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"


[global]
suppressDeprecationWarnings = true
showWarningOnDirectExecution = false

[runner]
magicEnabled = true
